name: Build

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
          
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          
      - name: Build with Maven
        run: mvn clean install    
      
          
      - name: Build and analyze with SonarQube
        uses: sonarsource/sonarcloud-github-action@master
        with:
          organization: 20110665
          token: ${{ secrets.SONAR_TOKEN }}
